server:
  port: 8086
spring:
  application:
    name: video-service
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.damao.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      damao:
        mapper: debug
        service: info
        controller: info