server:
  port: 8086
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.damao.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      damao:
        mapper: debug
        service: info
        controller: info
spring:
  application:
    name: video-service
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 200MB        # 设置单个文件最大大小为200MB
      max-request-size: 400MB